// Generated by dts-bundle v0.7.3
// Dependencies for this module:
//   ../../es6-promise

import { Promise } from 'es6-promise';

export class AppLauncher {
    static getReactDomConfig(): IReactDomConfig;
}
export interface IReactDomConfig {
    rootId: string;
    env: any;
}

export class TokenCache {
        /**
            *
            * @param request TokenRequest          The TokenRequest object
            * @param options ITokenRequestOptions  Optional ITokenRequestOptions
            */
        static getToken(request: TokenRequest, options?: ITokenRequestOptions): Promise<IToken | TokenRequestError>;
}
export interface ITokenRequestOptions {
        nonce: string;
        wpAjaxAdminUrl: string;
}
export interface IToken {
        name: string;
        expires: number;
        bearer: string;
}
export class TokenRequestError extends Error {
        data: ITokenResponse;
}
export interface ITokenResponse {
        status: string;
        error_codes: string;
        message: string;
        result: string;
}
export class TokenRequest {
        name: string;
        resourceId: string;
        constructor(name: string, resourceId: string);
        toString(): string;
}

